### ISSUE TITLE
Character display error in the Readme & code

### ISSUE THREAD

**Issue by azev77** [jjl3411/julia-FactorAugmentedVectorAR.jl#1]
Hi and thank you for this package!

There seems to be a problem with the characters in the readme & code:
![image](https://user-images.githubusercontent.com/7883904/99622213-b2e5d600-29f7-11eb-8ab6-1c8ea9e7094d.png)

**Comment by justinjjlee** [comment]
It seems like a display/encoding issue. Code should run properly.
